name: Pull Request Open

on:
  pull_request:

jobs:
    generate-matrix:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
      - uses: actions/checkout@v4

      - name: Set matrix
        id: set-matrix
        run: |
          export EVENT_NAME="${{github.event_name}}"
          export RUN_ATTEMPT="${{github.run_attempt}}"
          read -d '' COMMIT_MESSAGE << EOM || true
          ${{ github.event.head_commit.message }}
          EOM
          export COMMIT_MESSAGE
          echo "matrix=$(bash firmware/bin/generate_matrix.sh)" >> $GITHUB_OUTPUT
